### ISSUE TITLE
Exception raised on closing connection with Web driver (Selenium)

### ISSUE THREAD

**Issue by vincenzodibiaggio** [Behat/Behat#1011]
If a testsuite use the Selenium2Driver, session is not properly closed and after some time an exception will be raised:

`[WebDriver\Exception\UnknownError]                                            
  Session [ffcc81c9-cef1-4517-ab30-cb97b6114a47] was terminated due to TIMEOUT`
```
#0 /var/www/html/vendor/instaclick/php-webdriver/lib/WebDriver/AbstractWebDriver.php(141): WebDriver\Exception::factory(13, 'Session [08a112...')
#1 /var/www/html/vendor/instaclick/php-webdriver/lib/WebDriver/Session.php(157): WebDriver\AbstractWebDriver->curl('DELETE', '')
#2 /var/www/html/vendor/behat/mink-selenium2-driver/src/Selenium2Driver.php(348): WebDriver\Session->close()
#3 /var/www/html/vendor/behat/mink/src/Session.php(78): Behat\Mink\Driver\Selenium2Driver->stop()
#4 /var/www/html/vendor/behat/mink/src/Mink.php(186): Behat\Mink\Session->stop()
#5 /var/www/html/vendor/behat/mink/src/Mink.php(46): Behat\Mink\Mink->stopSessions()
#6 [internal function]: Behat\Mink\Mink->__destruct()
#7 {main}
```

chrome / hub logs:

```
chrome_1           | 11:05:37.783 INFO - Executing: [find element: By.xpath: //html])
chrome_1           | 11:05:37.843 INFO - Done: [find element: By.xpath: //html]
chrome_1           | 11:05:37.856 INFO - Executing: [get text: 5 [[ChromeDriver: chrome on LINUX (96b0e9603a8e164374fec11e9525e1bb)] -> xpath: //html]])
chrome_1           | 11:05:38.275 INFO - Done: [get text: 5 [[ChromeDriver: chrome on LINUX (96b0e9603a8e164374fec11e9525e1bb)] -> xpath: //html]]
chrome_1           | 11:05:38.290 INFO - Executing: [take screenshot])
chrome_1           | 11:05:38.457 INFO - Done: [take screenshot]
chrome_1           | 11:05:38.555 INFO - Executing: [delete all cookies])
chrome_1           | 11:05:38.589 INFO - Done: [delete all cookies]
hub_1              | 11:06:08.981 WARN - session ext. key 08a1122c-5413-445d-a4bb-3b0f7fa0bf58 has TIMED OUT due to client inactivity and will be released.
chrome_1           | 11:06:08.984 INFO - Executing: [delete session: 08a1122c-5413-445d-a4bb-3b0f7fa0bf58])
chrome_1           | 11:06:09.177 INFO - Done: [delete session: 08a1122c-5413-445d-a4bb-3b0f7fa0bf58]
```

IMHO, the webdriver close a session that do not exist and an exception will be raised here:

`vendor/instaclick/php-webdriver/lib/WebDriver/AbstractWebDriver.php`

```
// if not success, throw exception
        if ((int) $result['status'] !== 0) {
            throw WebDriverException::factory($result['status'], $message);
        }
```

because thre $result['status'] is 13.

If we call directly the proper function to close/delete sessions like

```if ($driver instanceof Selenium2Driver) {
        $driver->getWebDriverSession()->close();
        $driver->stop();
    }
```

an exception will be raised because of the result code that is 12 in this case.

Maybe this problem can be resolved with a final class that extends AbstractWebDriver.php

**Comment by vincenzodibiaggio** [comment]
Sorry, 
I've opened this issue in the proper project page (https://github.com/instaclick/php-webdriver/issues/75)
