### ISSUE TITLE
bug: "Class string does not exist"

### ISSUE THREAD

**Issue by florisluiten** [Behat/Behat#1328]
With version 3.8.0 a bug was introduced that was not present in 3.7.0.

In case a context is written with a type-hinted argument that is not a class, it seems to trigger the "Class \<type> does not exist" error. 

For example, our feature-file looks like this:

```
  Scenario: Listing jobs with salary range if salary range is known
    Given there is a job "Junior tester"
[...]
    Then "Junior tester" should be listed without salary range
```

With the corresponding context:

```php
classs JobListingContext extends FeatureContext
{
    /**
     * @Then :job should be listed without salary range
     */
    public function jobWithoutSalaryShouldNotShowSalary(string $job)
    {
        expect($this->jobListing)->toHaveJobWithoutSalaryRange($job);
    }
}
```

When the type-hint "string" is removed, the error is gone. The bug is not triggered in case the typehint is an actual class, it only seems to happen with simple types.

Full stacktrace:

```
  Then "Junior tester" should be listed without salary range
      Behat\Testwork\Call\Exception\FatalThrowableError: Fatal error: Class string does not exist in vendor/behat/behat/src/Behat/Behat/Transformation/Transformation/ReturnTypeTransformation.php:232
      Stack trace:
      #0 vendor/behat/behat/src/Behat/Behat/Transformation/Transformation/ReturnTypeTransformation.php(232): ReflectionClass->__construct()
      #1 [internal function]: Behat\Behat\Transformation\Transformation\ReturnTypeTransformation->Behat\Behat\Transformation\Transformation\{closure}()
      #2 vendor/behat/behat/src/Behat/Behat/Transformation/Transformation/ReturnTypeTransformation.php(157): array_filter()
      #3 vendor/behat/behat/src/Behat/Behat/Transformation/Transformation/ReturnTypeTransformation.php(70): Behat\Behat\Transformation\Transformation\ReturnTypeTransformation->getParameterClassNameByIndex()
      #4 vendor/behat/behat/src/Behat/Behat/Transformation/Transformation/TokenNameAndReturnTypeTransformation.php(66): Behat\Behat\Transformation\Transformation\ReturnTypeTransformation->supportsDefinitionAndArgument()
      #5 vendor/behat/behat/src/Behat/Behat/Transformation/Transformer/RepositoryArgumentTransformer.php(166): Behat\Behat\Transformation\Transformation\TokenNameAndReturnTypeTransformation->supportsDefinitionAndArgument()
      #6 vendor/behat/behat/src/Behat/Behat/Transformation/Transformer/RepositoryArgumentTransformer.php(123): Behat\Behat\Transformation\Transformer\RepositoryArgumentTransformer->transform()
      #7 vendor/behat/behat/src/Behat/Behat/Transformation/Transformer/RepositoryArgumentTransformer.php(86): Behat\Behat\Transformation\Transformer\RepositoryArgumentTransformer->applySimpleTransformations()
      #8 vendor/behat/behat/src/Behat/Behat/Transformation/Call/Filter/DefinitionArgumentsTransformer.php(103): Behat\Behat\Transformation\Transformer\RepositoryArgumentTransformer->transformArgument()
      #9 vendor/behat/behat/src/Behat/Behat/Transformation/Call/Filter/DefinitionArgumentsTransformer.php(64): Behat\Behat\Transformation\Call\Filter\DefinitionArgumentsTransformer->transformArgument()
      #10 vendor/behat/behat/src/Behat/Testwork/Call/CallCenter.php(116): Behat\Behat\Transformation\Call\Filter\DefinitionArgumentsTransformer->filterCall()
      #11 vendor/behat/behat/src/Behat/Testwork/Call/CallCenter.php(96): Behat\Testwork\Call\CallCenter->filterCall()
      #12 vendor/behat/behat/src/Behat/Behat/Tester/Runtime/RuntimeStepTester.php(125): Behat\Testwork\Call\CallCenter->makeCall()
      #13 vendor/behat/behat/src/Behat/Behat/Tester/Runtime/RuntimeStepTester.php(73): Behat\Behat\Tester\Runtime\RuntimeStepTester->testDefinition()
      #14 vendor/behat/behat/src/Behat/Behat/Hook/Tester/HookableStepTester.php(74): Behat\Behat\Tester\Runtime\RuntimeStepTester->test()
      #15 vendor/behat/behat/src/Behat/Behat/EventDispatcher/Tester/EventDispatchingStepTester.php(76): Behat\Behat\Hook\Tester\HookableStepTester->test()
      #16 vendor/behat/behat/src/Behat/Behat/Tester/StepContainerTester.php(59): Behat\Behat\EventDispatcher\Tester\EventDispatchingStepTester->test()
      #17 vendor/behat/behat/src/Behat/Behat/Tester/Runtime/RuntimeScenarioTester.php(76): Behat\Behat\Tester\StepContainerTester->test()
      #18 vendor/behat/behat/src/Behat/Behat/Hook/Tester/HookableScenarioTester.php(74): Behat\Behat\Tester\Runtime\RuntimeScenarioTester->test()
      #19 vendor/behat/behat/src/Behat/Behat/EventDispatcher/Tester/EventDispatchingScenarioTester.php(106): Behat\Behat\Hook\Tester\HookableScenarioTester->test()
      #20 vendor/behat/behat/src/Behat/Behat/Tester/Runtime/IsolatingScenarioTester.php(69): Behat\Behat\EventDispatcher\Tester\EventDispatchingScenarioTester->test()
      #21 vendor/behat/behat/src/Behat/Behat/Tester/Runtime/RuntimeFeatureTester.php(84): Behat\Behat\Tester\Runtime\IsolatingScenarioTester->test()
      #22 vendor/behat/behat/src/Behat/Behat/Hook/Tester/HookableFeatureTester.php(72): Behat\Behat\Tester\Runtime\RuntimeFeatureTester->test()
      #23 vendor/behat/behat/src/Behat/Behat/EventDispatcher/Tester/EventDispatchingFeatureTester.php(74): Behat\Behat\Hook\Tester\HookableFeatureTester->test()
      #24 vendor/behat/behat/src/Behat/Testwork/Tester/Runtime/RuntimeSuiteTester.php(63): Behat\Behat\EventDispatcher\Tester\EventDispatchingFeatureTester->test()
      #25 vendor/behat/behat/src/Behat/Testwork/Hook/Tester/HookableSuiteTester.php(73): Behat\Testwork\Tester\Runtime\RuntimeSuiteTester->test()
      #26 vendor/behat/behat/src/Behat/Testwork/EventDispatcher/Tester/EventDispatchingSuiteTester.php(75): Behat\Testwork\Hook\Tester\HookableSuiteTester->test()
      #27 vendor/behat/behat/src/Behat/Testwork/Tester/Runtime/RuntimeExercise.php(71): Behat\Testwork\EventDispatcher\Tester\EventDispatchingSuiteTester->test()
      #28 vendor/behat/behat/src/Behat/Testwork/EventDispatcher/Tester/EventDispatchingExercise.php(73): Behat\Testwork\Tester\Runtime\RuntimeExercise->test()
      #29 vendor/behat/behat/src/Behat/Testwork/Ordering/OrderedExercise.php(80): Behat\Testwork\EventDispatcher\Tester\EventDispatchingExercise->test()
      #30 vendor/behat/behat/src/Behat/Testwork/Tester/Cli/ExerciseController.php(149): Behat\Testwork\Ordering\OrderedExercise->test()
      #31 vendor/behat/behat/src/Behat/Testwork/Tester/Cli/ExerciseController.php(108): Behat\Testwork\Tester\Cli\ExerciseController->testSpecifications()
      #32 vendor/behat/behat/src/Behat/Testwork/Cli/Command.php(63): Behat\Testwork\Tester\Cli\ExerciseController->execute()
      #33 vendor/symfony/console/Command/Command.php(255): Behat\Testwork\Cli\Command->execute()
      #34 vendor/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run()
      #35 vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
      #36 vendor/behat/behat/src/Behat/Testwork/Cli/Application.php(124): Symfony\Component\Console\Application->doRun()
      #37 vendor/symfony/console/Application.php(149): Behat\Testwork\Cli\Application->doRun()
      #38 vendor/behat/behat/bin/behat(34): Symfony\Component\Console\Application->run()
```

**Comment by ciaranmcnulty** [comment]
Thanks for reporting, unfortunately I'm not able to reproduce immediately

The following passes:

```
  Scenario: By-type transformations don't error from scalar types
    Given a file named "features/scalar-transforms.feature" with:
      """
      Feature: Jobs

        Scenario: Listing jobs with salary range if salary range is known
          Then "Junior tester" should be listed without salary range
      """
    And a file named "features/bootstrap/FeatureContext.php" with:
      """
      <?php
      class FeatureContext implements Behat\Behat\Context\Context
      {
          /**
           * @Then :job should be listed without salary range
           */
          public function jobWithoutSalaryShouldNotShowSalary(string $job)
          {

          }
      }
      """
    When I run "behat -f progress --no-colors"
    Then it should pass
```

Is there something else causing it, maybe in your base FeatureContext class?

**Comment by florisluiten** [comment]
Thank you for your quick response. 

Since you could not reproduce it, I dig deeper and tried changing `job` to `jobTitle` and indeed it passes. It seems there is a transformer in the way. What's weird though, that this did work in version 3.7.0.

Anyhow, since I know that the fault entirely on my side, I will go fix my features :)

You can close this issue! Thanks again :+1:

**Comment by ciaranmcnulty** [comment]
This is still a bug I think - if you have time to help reproduce I'd appreciate it

**Comment by adamquaile** [comment]
I think I can help a little with this, as I'm having the same problem. 

https://github.com/Behat/Behat/blob/304661d4bc00934314c835c79fe36c0ce38da268/src/Behat/Behat/Transformation/Transformation/ReturnTypeTransformation.php#L232

For me this line of code is invoking `new ReflectionClass('string')` resulting in a `ReflectionException: class string does not exist`

I can see some logic to return null on `TypeError` and adding an extra catch block for `ReflectionException` fixes it for me, as does changing the condition above to `if ($t instanceof ReflectionNamedType && !$t->isBuiltin()) {`.

I haven't simplified it into a small reproducible test case but it's failing on the first step with a type-hinted string parameter, and it looks like it's because `ReturnTypeTransfomation` has this bug in the logic to decide if it's a class or not.

**Comment by ciaranmcnulty** [comment]
Thanks @adamquaile I suspected this from the stack trace but would love to write a failing test

**Comment by adamquaile** [comment]
If I get the chance, I'll try to create one

**Comment by adamquaile** [comment]
@ciaranmcnulty Here's one that causes the error for me: 

```
Feature:

  Scenario: By-type transformations don't error from scalar types
    Given a file named "features/scalar-transforms.feature" with:
      """
      Feature: Jobs

        Scenario: Listing jobs with salary range if salary range is known
          Then "Junior tester" should be listed with salary range:
          | Low  | 0    |
          | High | 1000 |
      """
    And a file named "features/bootstrap/FeatureContext.php" with:
      """
      <?php

      class Range {
        public $low;
        public $high;
      }

      class FeatureContext implements Behat\Behat\Context\Context
      {
          /**
           * @Transform
           */
           public function transformRangeInTable(Behat\Gherkin\Node\TableNode $table): Range
           {
               $range = new Range;
               $range->low = $table->getRowsHash()['Low'];
               $range->high = $table->getRowsHash()['High'];
               return $range;
           }

          /**
           * @Then :job should be listed with salary range:
           */
          public function jobWithoutSalaryShouldNotShowSalary(string $job, Range $range)
          {

          }
      }
      """
    When I run "behat -f progress --no-colors"
    Then it should pass
```

**Comment by ciaranmcnulty** [comment]
@adamquaile awesome thank you

**Comment by ciaranmcnulty** [comment]
Can you please check that 3.8.1 fixes it?

**Comment by adamquaile** [comment]
Yeah, that fixed it for me. Thanks for the quick fix and tag.

**Comment by florisluiten** [comment]
Thank you both for your help, I just tested with 3.8.1 and indeed it has been fixed!
