### ISSUE TITLE
8.1 issues when running behat with Symfony 5 deprecation notice is being converted to a fatal

### ISSUE THREAD

**Issue by frankmckechnie** [Behat/Behat#1419]
Using Symfony 5.4 and php 8.1

For some reason behat is failing. This should only be a deprecation but its treated as a fatal error only when running behat on cli.

```bash
PHP 8.1.13 (cli) (built: Dec 22 2022 14:52:37) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.13, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.13, Copyright (c), by Zend Technologies```

fatal error: During inheritance of JsonSerializable: Uncaught Behat\Testwork\Call\Exception\CallErrorException: 8192: Return type of Contentful\Delivery\SystemProperties\BaseSystemProperties::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/frankmckechnie/dev/gc-site/vendor/contentful/contentful/src/SystemProperties/BaseSystemProperties.php line 53 in /Users/frankmckechnie/dev/gc-site/vendor/behat/behat/src/Behat/Testwork/Call/Handler/RuntimeCallHandler.php:90


Stack trace:
#0 /Users/fm/dev/site/vendor/contentful/contentful/src/SystemProperties/BaseSystemProperties.php(19): Behat\Testwork\Call\Handler\RuntimeCallHandler->handleError(8192, 'Return type of ...', '/Users/fm...', 53)
#1 /Users/fm/dev/site/vendor/composer/ClassLoader.php(122): include('/Users/fm...')
#2 /Users/fm/dev/site/vendor/composer/ClassLoader.php(443): Composer\Autoload\ClassLoader::Composer\Autoload\{closure}('/Users/fm...')
#3 /Users/fm/dev/site/vendor/contentful/contentful/src/SystemProperties/LocalizedResource.php(14): Composer\Autoload\ClassLoader->loadClass('Contentful\\Deli...')
#4 /Users/fm/dev/site/vendor/composer/ClassLoader.php(122): include('/Users/fm...')
#5 /Users/fm/dev/site/vendor/composer/ClassLoader.php(443): Composer\Autoload\ClassLoader::Composer\Autoload\{closure}('/Users/fm...')
#6 /Users/fm/dev/site/vendor/contentful/contentful/src/SystemProperties/Asset.php(14): Composer\Autoload\ClassLoader->loadClass('Contentful\\Deli...')
#7 /Users/fm/dev/site/vendor/composer/ClassLoader.php(122): include('/Users/fm...')
#8 /Users/fm/dev/site/vendor/composer/ClassLoader.php(443): Composer\Autoload\ClassLoader::Composer\Autoload\{closure}('/Users/fm...')
#9 [internal function]: Composer\Autoload\ClassLoader->loadClass('Contentful\\Deli...')
#10 /Users/fm/dev/site/vendor/company/gc-contentful-extension/src/Entity/CmsResponse.php(164): unserialize('a:1:{i:0;O:33:"...')
#11 /Users/fm/dev/site/vendor/company/gc-contentful-extension/src/Client/DeliveryClient.php(104): GcContentfulExtension\Entity\CmsResponse->getData()
#12 /Users/fm/dev/site/vendor/company/gc-contentful-extension/src/Repository/Read/ContentfulRepository.php(47): GcContentfulExtension\Client\DeliveryClient->entries(Object(Contentful\Delivery\Query))
#13 /Users/fm/dev/site/vendor/company/gc-contentful-extension/src/Repository/Read/ContentfulRepository.php(27): GcContentfulExtension\Repository\Read\ContentfulRepository->entries(Object(Contentful\Delivery\Query), false)
#14 /Users/fm/dev/site/src/Repository/Read/Contentful/FuneralPlans/FuneralPlanRepository.php(25): GcContentfulExtension\Repository\Read\ContentfulRepository->entry(Object(Contentful\Delivery\Query), false)
#15 /Users/fm/dev/site/src/Repository/Read/Contentful/FuneralPlans/FuneralPlanRepository.php(37): App\Repository\Read\Contentful\FuneralPlans\FuneralPlanRepository->getFuneralPlanByKey('select', false)
#16 /Users/fm/dev/site/src/Provider/Purchase/PurchaseItemProvider.php(42): App\Repository\Read\Contentful\FuneralPlans\FuneralPlanRepository->getPurchaseJourneyPlanContentByKey('select', false)
#17 /Users/fm/dev/site/src/Factory/Purchase/v2/PurchaseDocumentFactory.php(99): App\Provider\Purchase\PurchaseItemProvider->getItemsForNativePlan('select', false)
#18 /Users/fm/dev/site/src/Factory/Purchase/v2/PurchaseDocumentFactory.php(58): App\Factory\Purchase\v2\PurchaseDocumentFactory->createDataBlock(Object(App\Entity\Purchase\Cart), false)
#19 /Users/fm/dev/site/src/Controller/Api/PurchaseDocumentController.php(63): App\Factory\Purchase\v2\PurchaseDocumentFactory->createDocumentEventFromRequest(Object(Symfony\Component\HttpFoundation\Request), '886b516c-665b-4...')
#20 /Users/fm/dev/site/tests/Behat/Site/ContainerPurchaseJourneyContext.php(285): App\Controller\Api\PurchaseDocumentController->retrieveDocument(Object(Symfony\Component\HttpFoundation\Request), '886b516c-665b-4...', 'download')
#21 /Users/fm/dev/site/vendor/behat/behat/src/Behat/Testwork/Call/Handler/RuntimeCallHandler.php(110): App\Tests\Behat\Site\ContainerPurchaseJourneyContext->iChooseToActionTheDocument('download', 'demands-and-nee...')
#22 /Users/fm/dev/site/vendor/behat/behat/src/Behat/Testwork/Call/Handler/RuntimeCallHandler.php(64): Behat\Testwork\Call\Handler\RuntimeCallHandler->executeCall(Object(Behat\Behat\Definition\Call\DefinitionCall))
#23 /Users/fm/dev/site/vendor/behat/behat/src/Behat/Testwork/Call/CallCenter.php(138): Behat\Testwork\Call\Handler\RuntimeCallHandler->handleCall(Object(Behat\Behat\Definition\Call\DefinitionCall))
#24 /Users/fm/dev/site/vendor/behat/behat/src/Behat/Testwork/Call/CallCenter.php(96): Behat\Testwork\Call\CallCenter->handleCall(Object(Behat\Behat\Definition\Call\DefinitionCall))
#25 /Users/fm/dev/site/vendor/behat/behat/src/Behat/Behat/Tester/Runtime/RuntimeStepTester.php(125): Behat\Testwork\Call\CallCenter->makeCall(Object(Behat\Behat\Definition\Call\DefinitionCall))
#26 /Users/fm/dev/site/vendor/behat/behat/src/Behat/Behat/Tester/Runtime/RuntimeStepTester.php(73): Behat\Behat\Tester\Runtime\RuntimeStepTester->testDefinition(Object(FriendsOfBehat\SymfonyExtension\Context\Environment\InitializedSymfonyExtensionEnvironment), Object(Behat\Gherkin\Node\FeatureNode), Object(Behat\Gherkin\Node\StepNode), Object(Behat\Behat\Definition\SearchResult), false)
#27 /Users/fm/dev/site/vendor/behat/behat/src/Behat/Behat/Hook/Tester/HookableStepTester.php(74): Behat\Behat\Tester\Runtime\RuntimeStepTester->test(Object(FriendsOfBehat\SymfonyExtension\Context\Environment\InitializedSymfonyExtensionEnvironment), Object(Behat\Gherkin\Node\FeatureNode), Object(Behat\Gherkin\Node\StepNode), false)
#28 /Users/fm/dev/site/vendor/behat/behat/src/Behat/Behat/EventDispatcher/Tester/EventDispatchingStepTester.php(76): Behat\Behat\Hook\Tester\HookableStepTester->test(Object(FriendsOfBehat\SymfonyExtension\Context\Environment\InitializedSymfonyExtensionEnvironment), Object(Behat\Gherkin\Node\FeatureNode), Object(Behat\Gherkin\Node\StepNode), false)
#29 /Users/fm/dev/site/vendor/behat/behat/src/Behat/Behat/Tester/StepContainerTester.php(59): Behat\Behat\EventDispatcher\Tester\EventDispatchingStepTester->test(Object(FriendsOfBehat\SymfonyExtension\Context\Environment\InitializedSymfonyExtensionEnvironment), Object(Behat\Gherkin\Node\FeatureNode), Object(Behat\Gherkin\Node\StepNode), false)
#30 /Users/fm/dev/site/vendor/behat/behat/src/Behat/Behat/Tester/Runtime/RuntimeScenarioTester.php(76): Behat\Behat\Tester\StepContainerTester->test(Object(FriendsOfBehat\SymfonyExtension\Context\Environment\InitializedSymfonyExtensionEnvironment), Object(Behat\Gherkin\Node\FeatureNode), Object(Behat\Gherkin\Node\ScenarioNode), false)
#31 /Users/fm/dev/site/vendor/behat/behat/src/Behat/Behat/Hook/Tester/HookableScenarioTester.php(74): Behat\Behat\Tester\Runtime\RuntimeScenarioTester->test(Object(FriendsOfBehat\SymfonyExtension\Context\Environment\InitializedSymfonyExtensionEnvironment), Object(Behat\Gherkin\Node\FeatureNode), Object(Behat\Gherkin\Node\ScenarioNode), false)
#32 /Users/fm/dev/site/vendor/behat/behat/src/Behat/Behat/EventDispatcher/Tester/EventDispatchingScenarioTester.php(106): Behat\Behat\Hook\Tester\HookableScenarioTester->test(Object(FriendsOfBehat\SymfonyExtension\Context\Environment\InitializedSymfonyExtensionEnvironment), Object(Behat\Gherkin\Node\FeatureNode), Object(Behat\Gherkin\Node\ScenarioNode), false)
#33 /Users/fm/dev/site/vendor/behat/behat/src/Behat/Behat/Tester/Runtime/IsolatingScenarioTester.php(69): Behat\Behat\EventDispatcher\Tester\EventDispatchingScenarioTester->test(Object(FriendsOfBehat\SymfonyExtension\Context\Environment\InitializedSymfonyExtensionEnvironment), Object(Behat\Gherkin\Node\FeatureNode), Object(Behat\Gherkin\Node\ScenarioNode), false)
#34 /Users/fm/dev/site/vendor/behat/behat/src/Behat/Behat/Tester/Runtime/RuntimeFeatureTester.php(84): Behat\Behat\Tester\Runtime\IsolatingScenarioTester->test(Object(FriendsOfBehat\SymfonyExtension\Context\Environment\UninitializedSymfonyExtensionEnvironment), Object(Behat\Gherkin\Node\FeatureNode), Object(Behat\Gherkin\Node\ScenarioNode), false)
#35 /Users/fm/dev/site/vendor/behat/behat/src/Behat/Behat/Hook/Tester/HookableFeatureTester.php(72): Behat\Behat\Tester\Runtime\RuntimeFeatureTester->test(Object(FriendsOfBehat\SymfonyExtension\Context\Environment\UninitializedSymfonyExtensionEnvironment), Object(Behat\Gherkin\Node\FeatureNode), false)
#36 /Users/fm/dev/site/vendor/behat/behat/src/Behat/Behat/EventDispatcher/Tester/EventDispatchingFeatureTester.php(74): Behat\Behat\Hook\Tester\HookableFeatureTester->test(Object(FriendsOfBehat\SymfonyExtension\Context\Environment\UninitializedSymfonyExtensionEnvironment), Object(Behat\Gherkin\Node\FeatureNode), false)
#37 /Users/fm/dev/site/vendor/behat/behat/src/Behat/Testwork/Tester/Runtime/RuntimeSuiteTester.php(63): Behat\Behat\EventDispatcher\Tester\EventDispatchingFeatureTester->test(Object(FriendsOfBehat\SymfonyExtension\Context\Environment\UninitializedSymfonyExtensionEnvironment), Object(Behat\Gherkin\Node\FeatureNode), false)
#38 /Users/fm/dev/site/vendor/behat/behat/src/Behat/Testwork/Hook/Tester/HookableSuiteTester.php(73): Behat\Testwork\Tester\Runtime\RuntimeSuiteTester->test(Object(FriendsOfBehat\SymfonyExtension\Context\Environment\UninitializedSymfonyExtensionEnvironment), Object(Behat\Testwork\Specification\GroupedSpecificationIterator), false)
#39 /Users/fm/dev/site/vendor/behat/behat/src/Behat/Testwork/EventDispatcher/Tester/EventDispatchingSuiteTester.php(75): Behat\Testwork\Hook\Tester\HookableSuiteTester->test(Object(FriendsOfBehat\SymfonyExtension\Context\Environment\UninitializedSymfonyExtensionEnvironment), Object(Behat\Testwork\Specification\GroupedSpecificationIterator), false)
#40 /Users/fm/dev/site/vendor/behat/behat/src/Behat/Testwork/Tester/Runtime/RuntimeExercise.php(71): Behat\Testwork\EventDispatcher\Tester\EventDispatchingSuiteTester->test(Object(FriendsOfBehat\SymfonyExtension\Context\Environment\UninitializedSymfonyExtensionEnvironment), Object(Behat\Testwork\Specification\GroupedSpecificationIterator), false)
#41 /Users/fm/dev/site/vendor/behat/behat/src/Behat/Testwork/EventDispatcher/Tester/EventDispatchingExercise.php(73): Behat\Testwork\Tester\Runtime\RuntimeExercise->test(Array, false)
#42 /Users/fm/dev/site/vendor/behat/behat/src/Behat/Testwork/Ordering/OrderedExercise.php(80): Behat\Testwork\EventDispatcher\Tester\EventDispatchingExercise->test(Array, false)
#43 /Users/fm/dev/site/vendor/behat/behat/src/Behat/Testwork/Tester/Cli/ExerciseController.php(149): Behat\Testwork\Ordering\OrderedExercise->test(Array, false)
#44 /Users/fm/dev/site/vendor/behat/behat/src/Behat/Testwork/Tester/Cli/ExerciseController.php(108): Behat\Testwork\Tester\Cli\ExerciseController->testSpecifications(Object(Symfony\Component\Console\Input\ArgvInput), Array)
#45 /Users/fm/dev/site/vendor/behat/behat/src/Behat/Testwork/Cli/Command.php(63): Behat\Testwork\Tester\Cli\ExerciseController->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#46 /Users/fm/dev/site/vendor/symfony/console/Command/Command.php(298): Behat\Testwork\Cli\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#47 /Users/fm/dev/site/vendor/symfony/console/Application.php(1043): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#48 /Users/fm/dev/site/vendor/symfony/console/Application.php(304): Symfony\Component\Console\Application->doRunCommand(Object(Behat\Testwork\Cli\Command), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#49 /Users/fm/dev/site/vendor/behat/behat/src/Behat/Testwork/Cli/Application.php(124): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#50 /Users/fm/dev/site/vendor/symfony/console/Application.php(171): Behat\Testwork\Cli\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#51 /Users/fm/dev/site/vendor/behat/behat/bin/behat(34): Symfony\Component\Console\Application->run()
#52 /Users/fm/dev/site/vendor/bin/behat(120): include('/Users/fm...')
#53 {main} in /Users/fm/dev/site/vendor/contentful/contentful/src/SystemProperties/BaseSystemProperties.php on line 19
make: *** [gc-integration-container] Error 255

**Comment by frankmckechnie** [comment]
I have override the default error caller to ignore E_DEPRECATED, should this not be default?

```yaml default:
  calls:
    #  As behat was converting e-deprecated errors to a fatal you can override it here
    #  E_ALL & ~E_USER_DEPRECATED & ~E_DEPRECATED
    error_reporting: 8191```

**Comment by carlos-granados** [comment]
@acoulton I don't think this is really a problem with Behat. Behat is configured to run by default with the `E_ALL` level so it is expected to fail on unhandled deprecations like this one. So I think we should close this issue. What do you think?

**Comment by acoulton** [comment]
@carlos-granados agreed - changing the default would be a BC break and people have different opinions on whether/when deprecated should fail.

 The error level is configurable (although I'm not sure if that's documented at the moment) so that solves this.
